CREATE TABLE MAE
(
    CPF_MAE NUMBER(12) CONSTRAINT PK_CPF_MAE PRIMARY KEY,
    NOME_MAE VARCHAR2(30),
    TELEFONE NUMBER(12),
    DATA_NASC_MAE DATE,
    RUA VARCHAR2(30),
    NUMERO NUMBER(3)
);
CREATE TABLE MEDICO
(
    CRM NUMBER(13) CONSTRAINT PK_CRM PRIMARY KEY,
    ESPECIALIDADE VARCHAR2(30),
    NOME_MEDICO VARCHAR2(30),
    TELEFONE NUMBER(12)
);
CREATE TABLE BEBE
(
    ID_BEBE NUMBER(10) CONSTRAINT PK_ID_BEBE PRIMARY KEY,
    ALTURA NUMBER(2,2),
    NOME_BEBE VARCHAR2(30),
    DATA_NASC DATE,
    PESO NUMBER(3,2),
    FK_MEDICO_CRM NUMBER(13),
    FK_MAE_CPF NUMBER(12),
    FOREIGN KEY (FK_MEDICO_CRM) REFERENCES MEDICO (CRM),
    FOREIGN KEY (FK_MAE_CPF) REFERENCES MAE (CPF_MAE)
);
