CREATE TABLE CLIENTES
(  
    CPF_CLI NUMBER(12) CONSTRAINT PK_CPF_CLI PRIMARY KEY,
    NOME_CLI VARCHAR2(40),
    RUA VARCHAR2(30),
    CEP NUMBER(15)
);

CREATE TABLE PRODUTOS
(
    COD_PROD NUMBER(12) CONSTRAINT PK_COD_PROD PRIMARY KEY,
    NOME_PRODUTO VARCHAR2(30),
    FABRICANTE_PRODUTO VARCHAR2(30),
    VALOR_PRODUTO NUMBER(10,2)
);

CREATE TABLE PODE_COMPRAR
(
    ID_COMPRA NUMBER(12) CONSTRAINT PK_ID_COMPRA PRIMARY KEY,
    DATA_COMPRA DATE,
    FORMA_PAG_COMPRA VARCHAR2(30),
    FK_CLIENTES_CPF_CLI NUMBER(12),
    FK_PRODUTOS_COD_PRODUTO NUMBER(12),
    FOREIGN KEY (FK_CLIENTES_CPF_CLI) REFERENCES CLIENTES(CPF_CLI),
    FOREIGN KEY (FK_PRODUTOS_COD_PRODUTO) REFERENCES PRODUTOS(COD_PROD)
);

CREATE TABLE TELEFONE
(
    ID_TELEFONE NUMBER(5) CONSTRAINT PK_ID_TELEFONE PRIMARY KEY,
    TELEFONE1 NUMBER(12),
    TELEFONE2 NUMBER(12),
    TELEFONE3 NUMBER(12),
    FK_CLIENTES_CPF_CLI NUMBER(12),
    FOREIGN KEY (FK_CLIENTES_CPF_CLI) REFERENCES CLIENTES(CPF_CLI)
);

DROP TABLE CLIENTES;
DROP TABLE PRODUTOS;
DROP TABLE PODE_COMPRAR;
DROP TABLE TELEFONE;