CREATE TABLE TELEFONES(
    TELEFONE_1 NUMBER(11) CONSTRAINT TELEFONE_1 PRIMARY KEY,
    TELEFONE_2 NUMBER(11),
    TELEFONE_3 NUMBER(11)
);

CREATE TABLE VENDAS(
    NOTA_FISCAL NUMBER(11) CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY,
    data_venda DATE,
    QUANTIDADE NUMBER(10)
);

CREATE TABLE CLIENTE(
    CPF_CLIENTE NUMBER(11) CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(50) NOT NULL,
    RUA VARCHAR2(50),
    CEP NUMBER(8),
    FK_TELEFONE NUMBER(11),
    FK_VENDAS_NF NUMBER(9),
    FOREIGN KEY (FK_TELEFONE) REFERENCES TELEFONES (TELEFONE_1),
    FOREIGN KEY (FK_VENDAS_NF) REFERENCES VENDAS (NOTA_FISCAL)
);