CREATE TABLE TELEFONES (
    ID_FONE NUMBER(11) CONSTRAINT PK_ID_FONE PRIMARY KEY,
    TELEFONE_1 NUMBER(11),
    TELEFONE_2 NUMBER(11),
    TELEFONE_3 NUMBER(11)
);
CREATE TABLE VENDAS(
    NOTA_FISCAL NUMBER(11) CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY,
    data_venda DATE,
    QUANTIDADE NUMBER(10)
);
CREATE TABLE PRODUTO(
    COD_PRODUTO NUMBER(10) CONSTRAINT PK_COD_PROD PRIMARY KEY,
    NOME_PRODUTO VARCHAR2(50),
    QUANTIDADE_PRODUTO NUMBER(10),
    FK_VENDAS_NF NUMBER(11),
    FOREIGN KEY (FK_VENDAS_NF) REFERENCES VENDAS (NOTA_FISCAL)
);
CREATE TABLE CLIENTE (
    CPF_CLIENTE NUMBER(11) CONSTRAINT PK_CPF_CLIENTE PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(50) NOT NULL,
    RUA VARCHAR2(50),
    CEP NUMBER(8),
    FK_TELEFONE NUMBER(11),
    FK_VENDAS_NF NUMBER(11),
    FOREIGN KEY (FK_TELEFONE) REFERENCES TELEFONES (ID_FONE),
    FOREIGN KEY (FK_VENDAS_NF) REFERENCES VENDAS (NOTA_FISCAL)
);